plugins {
    id 'java'
    id 'idea'
    id 'fabric-loom' version '1.7-SNAPSHOT'
}

base {
    archivesName = "${mod_id}-fabric-${minecraft_version}"
}

repositories {
    mavenCentral()
    maven { url "https://maven.blamejared.com/" } // JEI
    maven { url "https://maven.shedaniel.me/" }   // Cloth Config
    maven { url "https://maven.terraformersmc.com" } // ModMenu
    maven { url 'https://maven.ladysnake.org/releases' } // Trinkets
    maven {
        url "https://cursemaven.com"
        content { includeGroup "curse.maven" }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    // Mojang official mappings only
    mappings loom.officialMojangMappings()

    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
    implementation project(":common")

    // JEI
    modCompileOnlyApi "mezz.jei:jei-${minecraft_version}-fabric-api:${rootProject.jei_version}"
    modRuntimeOnly "mezz.jei:jei-${minecraft_version}-fabric:${rootProject.jei_version}"

    // Cloth Config + ModMenu
    modApi include("me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_fabric_version}")
    modImplementation "com.terraformersmc:modmenu:${rootProject.mod_menu_version}"

    // Trinkets
    modImplementation "dev.emi:trinkets:${rootProject.trinkets_version}"


    // Lootr
    modImplementation "curse.maven:lootr-fabric-615106:6354237"
}

loom {
    if (project(":common").file("src/main/resources/${mod_id}.accesswidener").exists()) {
        accessWidenerPath.set(project(":common").file("src/main/resources/${mod_id}.accesswidener"))
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("run")
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    source(project(":common").sourceSets.main.allSource)
    options.encoding = 'UTF-8'
    options.release.set(21)
}

processResources {
    from project(":common").sourceSets.main.resources
}
