plugins {
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.+'
}

base {
    archivesName = "${mod_id}-neoforge-${minecraft_version}"
}

repositories {
    mavenCentral()
    maven { url "https://maven.blamejared.com/" }
    maven { url "https://maven.theillusivec4.top/" }
    maven {
        url "https://cursemaven.com"
        content { includeGroup "curse.maven" }
    }
}

neoForge {
    version = neoforge_version

    runs {
        client {
            client()
            gameDirectory = file('run')
            sourceSet = sourceSets.main
        }
        server {
            server()
            gameDirectory = file('run')
            sourceSet = sourceSets.main
        }
        data {
            data()
            gameDirectory = file('run')
            programArguments = [
                    "--mod", mod_id,
                    "--all",
                    "--output", file('src/generated/resources/').absolutePath,
                    "--existing", file('src/main/resources/').absolutePath
            ]
            sourceSet = sourceSets.main
        }
    }

    mods {
        register(mod_id) {
            sourceSet(sourceSets.main)
            sourceSet(project(":common").sourceSets.main)
        }
    }
}

sourceSets {
    main {
        resources {
            srcDir 'src/generated/resources'
        }
    }
}

dependencies {
    implementation project(":common")

    annotationProcessor "org.spongepowered:mixin:0.8.5-SNAPSHOT:processor"

    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${rootProject.jei_version}"
    runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${rootProject.jei_version}"

    implementation "top.theillusivec4.curios:curios-neoforge:${rootProject.curios_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(21)
}

processResources {
    inputs.property 'version', project.version
    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: project.version
    }
}

tasks.named('jar', Jar) {
    from(project(':common').sourceSets.main.output)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
